### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by ptoews** [torch-points3d/torch-points-kernels#90] opened 2022-04-12 10:32 UTC
What's the reason for requiring numpy <1.20? Is it possible to support newer versions soon?

**Comment by CCInc** [comment] 2022-04-12 17:10
Hi, the issue is that the version of Numba we use does not support later versions. I will see if we can upgrade when I get the chance.

**Comment by yuchenlichuck** [comment] 2022-04-17 10:38
hi, please check at your early convenience  or I can help to check, I find there will be a conflict for sharedarray, because it need the numpy version that is higher than 1.21

**Comment by yuchenlichuck** [comment] 2022-04-20 12:02
I test the code. The problem would be here: 

`/home/liy0r/anaconda3/envs/fd3d/lib/python3.7/site-packages/numba/core/ir_utils.py:1526: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  and def_val == getattr(numpy, value)):
E.EE.
======================================================================
ERROR: test_batch (test.test_metrics.TestInstanceIou)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/test_metrics.py", line 44, in test_batch
    ious = instance_iou(proposed_instances, gt_instances, batch=batch)
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/../torch_points_kernels/metrics.py", line 101, in instance_iou
    batch.numpy(),
TypeError: expected dtype object, got 'numpy.dtype[float64]'

======================================================================
ERROR: test_same (test.test_metrics.TestInstanceIou)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/__init__.py", line 7, in wrapped_func
    return func(*args, **kwargs)
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/test_metrics.py", line 72, in test_same
    ious = instance_iou(proposed_instances, gt_instances)
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/../torch_points_kernels/metrics.py", line 101, in instance_iou
    batch.numpy(),
TypeError: expected dtype object, got 'numpy.dtype[float64]'

======================================================================
ERROR: test_simple (test.test_metrics.TestInstanceIou)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/test_metrics.py", line 26, in test_simple
    ious = instance_iou(proposed_instances, gt_instances)
  File "/home/liy0r/cvpr/Stratified-Transformer/torch-points-kernels/test/../torch_points_kernels/metrics.py", line 101, in instance_iou
    batch.numpy(),
TypeError: expected dtype object, got 'numpy.dtype[float64]'
`

**Comment by Stakhan** [comment] 2022-05-11 12:54
Hi there,
I gave a try to the following combination of dependencies:
```
numba==0.55.1
numpy==1.21.0
torch==1.10.0+cu113
scikit-learn==1.0.2
```
And I was able to run the tests flawlessly:
```
~/torch-points-kernels$ python -m unittest
................................
----------------------------------------------------------------------
Ran 32 tests in 15.456s

OK
```
Couldn't go higher than NumPy 1.21 though, because it isn't supported by numba 0.55.1.

Since the [current requirements](https://github.com/torch-points3d/torch-points-kernels/blob/512033cbf3f1091420a9a9c12ed45ca7bef477c1/setup.py#L82) do not impose a constraint on numba, I would suggest to relax the numpy requirement to `numpy==1.21`  or `numpy<=1.21`. How does that sound @CCInc?

**Comment by CCInc** [comment] 2022-06-27 17:10
Sorry, I missed this thread. @Stakhan `numpy<=1.21` sounds good to me. 

It looks like numba 0.56 will support numpy 1.22, you will have to wait until that's released in order to upgrade @yuchenlichuck (https://github.com/numba/numba/issues/7754)

**Comment by Stakhan** [comment] 2022-07-01 11:55
No problem. Thanks for adding the modification.

**Comment by CCInc** [comment] 2022-07-01 17:55
I'll close the issue for now, once the new version of numba comes out, we can reassess and try to update again to support numpy 1.22.

**Closed by CCInc** 2022-07-01 17:55 UTC

**Comment by CiSong10** [comment] 2025-05-24 01:15
Hi, Numba has been upgraded to 0.61.2 by the time of this comment, hope torch-points-kernels can be updated as well! By now the latest 0.7.0 still shows the `torch-points-kernels 0.7.0 requires numpy<1.20` error
